# Actions Name

name: GetSanookData

# 在什么时候触发， push 是 git push 时触发，可以设置定时
on: 
  workflow_dispatch:
  pull_request:
    branches:
      - main
  # push:
    # branches: [ dev ]
  # pull_request:
  #   branches: [ main ]
  schedule:
    - cron: "*/5 * * * *"
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install beautifulsoup4

      - name: Update SanookJson
        run: |
          cd json
          python get_sanook_json.py

      - name: Commit SanookJson
        run: |
          git config --global user.email 2556940481@qq.com
          git config --global user.name xiao_chang
          git add .
          #git commit -m"action:`date +'%Y-%m-%d'`"
          git commit -m"action:`date`"
          git pull --rebase
      - name: Push SanookJson Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "main"

